---
- included tasks: patch-linux.yml
  when: os is match ("rhel.*")

- included tasks: patch-windows.yml
  when: os is match ("windows.*") or os is match ("2016.*") or os is match ("2019.*") or os is match ("2022.*") or os is match ("2012.*")
