---
- name: Install Windows Updates
  ansible.windows.win_updates:
    category_names: "{{ categories | default('*') }}"
    reboot: "{{ reboot_server | default('true') }}"
    accept_list: "{{ accept_packages | default(omit) }}"
    reject_list: "{{ reject_packages | default(omit) }}"
  register: patchresult
