---
- name: Install chocolatey and chrome
  hosts: windows-server
  gather_facts: yes

  tasks:
  - name: Install chocolatey
    win_chocolatey:
      name:
      - chocolatey
      - chocolatey-core.extension
      state: present

  - name: Install chocolatey
    win_chocolatey:
      name:
      - googlechrome
      state: latest
      ignore_checksums: yes
