---
- name: Start an EC2 instance using AWS CLI
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Describe instances
      command: aws ec2 describe-instances --region us-east-1
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_KEY') }}"
