---
- name: Start EC2
  hosts: localhost
  connection: local

  tasks:
    - name: Start Maintenance Page Server
      amazon.aws.ec2:
        region: "us-east-1"
        instance_ids:
          - "i-0a1bd6791ea0e4432"
        state: started
      when: ec2_info.instances[0].state.name == 'stopped'
