---
- name: Test
  hosts: localhost
  connection: local

- name: Describe instances
  ansible.builtin.shell: aws ec2 describe-instances --region us-east-2
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_KEY') }}"
