---
- name: Patch Windows Servers
  hosts: Windows-Server
  tasks:
    - name: Install all security, critical, and rollup updates without a scheduled task
      ansible.windows.win.updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
   
